apiVersion: v1
kind: Service
metadata:
  name: growthv16-service
  namespace: growth-v16
spec:
  selector:
    app: growthv16
  ports:
    - name: grpc
      port: 8085
      targetPort: 8085
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort