apiVersion: v1
kind: Service
metadata:
  name: usergrowth-headless
  namespace: growth-v16
spec:
  clusterIP: None
  selector:
    app: growthv16
  ports:
    - name: grpc
      port: 8085
      targetPort: 8085
    - name: http
      port: 8080
      targetPort: 8080