// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: user_groth.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for UserCoin service
type ListTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{0}
}

type ListTasksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*TbCoinTask `protobuf:"bytes,1,rep,name=dataList,proto3" json:"dataList,omitempty"`
}

func (x *ListTasksReply) Reset() {
	*x = ListTasksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReply) ProtoMessage() {}

func (x *ListTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReply.ProtoReflect.Descriptor instead.
func (*ListTasksReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksReply) GetDataList() []*TbCoinTask {
	if x != nil {
		return x.DataList
	}
	return nil
}

type UserCoinInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserCoinInfoRequest) Reset() {
	*x = UserCoinInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoinInfoRequest) ProtoMessage() {}

func (x *UserCoinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoinInfoRequest.ProtoReflect.Descriptor instead.
func (*UserCoinInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{2}
}

func (x *UserCoinInfoRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserCoinInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TbCoinUser `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserCoinInfoReply) Reset() {
	*x = UserCoinInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoinInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoinInfoReply) ProtoMessage() {}

func (x *UserCoinInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoinInfoReply.ProtoReflect.Descriptor instead.
func (*UserCoinInfoReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{3}
}

func (x *UserCoinInfoReply) GetData() *TbCoinUser {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserCoinDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UserCoinDetailsRequest) Reset() {
	*x = UserCoinDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoinDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoinDetailsRequest) ProtoMessage() {}

func (x *UserCoinDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoinDetailsRequest.ProtoReflect.Descriptor instead.
func (*UserCoinDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{4}
}

func (x *UserCoinDetailsRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserCoinDetailsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserCoinDetailsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UserCoinDetailsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*TbCoinDetail `protobuf:"bytes,1,rep,name=dataList,proto3" json:"dataList,omitempty"`
	Total    int32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *UserCoinDetailsReply) Reset() {
	*x = UserCoinDetailsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoinDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoinDetailsReply) ProtoMessage() {}

func (x *UserCoinDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoinDetailsReply.ProtoReflect.Descriptor instead.
func (*UserCoinDetailsReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{5}
}

func (x *UserCoinDetailsReply) GetDataList() []*TbCoinDetail {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *UserCoinDetailsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserCoinChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TaskName string `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"` //为什么不用task_id，因为认为u名称更好记住
	Coin     int32  `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (x *UserCoinChangeRequest) Reset() {
	*x = UserCoinChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoinChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoinChangeRequest) ProtoMessage() {}

func (x *UserCoinChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoinChangeRequest.ProtoReflect.Descriptor instead.
func (*UserCoinChangeRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{6}
}

func (x *UserCoinChangeRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserCoinChangeRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *UserCoinChangeRequest) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

type UserCoinChangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *TbCoinUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserCoinChangeReply) Reset() {
	*x = UserCoinChangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCoinChangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoinChangeReply) ProtoMessage() {}

func (x *UserCoinChangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoinChangeReply.ProtoReflect.Descriptor instead.
func (*UserCoinChangeReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{7}
}

func (x *UserCoinChangeReply) GetUser() *TbCoinUser {
	if x != nil {
		return x.User
	}
	return nil
}

// Messages for UserGrade service
type ListGradesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGradesRequest) Reset() {
	*x = ListGradesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesRequest) ProtoMessage() {}

func (x *ListGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesRequest.ProtoReflect.Descriptor instead.
func (*ListGradesRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{8}
}

type ListGradesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*TbGradeInfo `protobuf:"bytes,1,rep,name=dataList,proto3" json:"dataList,omitempty"`
}

func (x *ListGradesReply) Reset() {
	*x = ListGradesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGradesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesReply) ProtoMessage() {}

func (x *ListGradesReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesReply.ProtoReflect.Descriptor instead.
func (*ListGradesReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{9}
}

func (x *ListGradesReply) GetDataList() []*TbGradeInfo {
	if x != nil {
		return x.DataList
	}
	return nil
}

type ListGradePrivilegeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GradeId int32 `protobuf:"varint,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
}

func (x *ListGradePrivilegeRequest) Reset() {
	*x = ListGradePrivilegeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGradePrivilegeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradePrivilegeRequest) ProtoMessage() {}

func (x *ListGradePrivilegeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradePrivilegeRequest.ProtoReflect.Descriptor instead.
func (*ListGradePrivilegeRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{10}
}

func (x *ListGradePrivilegeRequest) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

type ListGradePrivilegeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataList []*TbGradePrivilege `protobuf:"bytes,1,rep,name=dataList,proto3" json:"dataList,omitempty"`
}

func (x *ListGradePrivilegeReply) Reset() {
	*x = ListGradePrivilegeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGradePrivilegeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradePrivilegeReply) ProtoMessage() {}

func (x *ListGradePrivilegeReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradePrivilegeReply.ProtoReflect.Descriptor instead.
func (*ListGradePrivilegeReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{11}
}

func (x *ListGradePrivilegeReply) GetDataList() []*TbGradePrivilege {
	if x != nil {
		return x.DataList
	}
	return nil
}

type CheckUserPrivilegeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Product  string `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Function string `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CheckUserPrivilegeRequest) Reset() {
	*x = CheckUserPrivilegeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserPrivilegeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPrivilegeRequest) ProtoMessage() {}

func (x *CheckUserPrivilegeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPrivilegeRequest.ProtoReflect.Descriptor instead.
func (*CheckUserPrivilegeRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{12}
}

func (x *CheckUserPrivilegeRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CheckUserPrivilegeRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *CheckUserPrivilegeRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

type CheckUserPrivilegeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data bool `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CheckUserPrivilegeReply) Reset() {
	*x = CheckUserPrivilegeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUserPrivilegeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPrivilegeReply) ProtoMessage() {}

func (x *CheckUserPrivilegeReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPrivilegeReply.ProtoReflect.Descriptor instead.
func (*CheckUserPrivilegeReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{13}
}

func (x *CheckUserPrivilegeReply) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type UserGradeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserGradeInfoRequest) Reset() {
	*x = UserGradeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGradeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGradeInfoRequest) ProtoMessage() {}

func (x *UserGradeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGradeInfoRequest.ProtoReflect.Descriptor instead.
func (*UserGradeInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{14}
}

func (x *UserGradeInfoRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserGradeInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TbGradeInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserGradeInfoReply) Reset() {
	*x = UserGradeInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGradeInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGradeInfoReply) ProtoMessage() {}

func (x *UserGradeInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGradeInfoReply.ProtoReflect.Descriptor instead.
func (*UserGradeInfoReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{15}
}

func (x *UserGradeInfoReply) GetData() *TbGradeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserGradeChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Score int32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *UserGradeChangeRequest) Reset() {
	*x = UserGradeChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGradeChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGradeChangeRequest) ProtoMessage() {}

func (x *UserGradeChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGradeChangeRequest.ProtoReflect.Descriptor instead.
func (*UserGradeChangeRequest) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{16}
}

func (x *UserGradeChangeRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserGradeChangeRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UserGradeChangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TbGradeUser `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserGradeChangeReply) Reset() {
	*x = UserGradeChangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGradeChangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGradeChangeReply) ProtoMessage() {}

func (x *UserGradeChangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGradeChangeReply.ProtoReflect.Descriptor instead.
func (*UserGradeChangeReply) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{17}
}

func (x *UserGradeChangeReply) GetData() *TbGradeUser {
	if x != nil {
		return x.Data
	}
	return nil
}

//数据库模型
// tb_coin_detail
type TbCoinDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid        int32  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	TaskId     int32  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Coin       int32  `protobuf:"varint,4,opt,name=coin,proto3" json:"coin,omitempty"`
	SysCreated string `protobuf:"bytes,5,opt,name=sys_created,json=sysCreated,proto3" json:"sys_created,omitempty"`
	SysUpdate  string `protobuf:"bytes,6,opt,name=sys_update,json=sysUpdate,proto3" json:"sys_update,omitempty"`
}

func (x *TbCoinDetail) Reset() {
	*x = TbCoinDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TbCoinDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbCoinDetail) ProtoMessage() {}

func (x *TbCoinDetail) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbCoinDetail.ProtoReflect.Descriptor instead.
func (*TbCoinDetail) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{18}
}

func (x *TbCoinDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TbCoinDetail) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TbCoinDetail) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TbCoinDetail) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *TbCoinDetail) GetSysCreated() string {
	if x != nil {
		return x.SysCreated
	}
	return ""
}

func (x *TbCoinDetail) GetSysUpdate() string {
	if x != nil {
		return x.SysUpdate
	}
	return ""
}

// tb_coin_task
type TbCoinTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Task       string `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Coin       int32  `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
	Limit      int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Start      string `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	SysCreated string `protobuf:"bytes,6,opt,name=sys_created,json=sysCreated,proto3" json:"sys_created,omitempty"`
	SysUpdated string `protobuf:"bytes,7,opt,name=sys_updated,json=sysUpdated,proto3" json:"sys_updated,omitempty"`
	SysStatus  int32  `protobuf:"varint,8,opt,name=sys_status,json=sysStatus,proto3" json:"sys_status,omitempty"`
}

func (x *TbCoinTask) Reset() {
	*x = TbCoinTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TbCoinTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbCoinTask) ProtoMessage() {}

func (x *TbCoinTask) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbCoinTask.ProtoReflect.Descriptor instead.
func (*TbCoinTask) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{19}
}

func (x *TbCoinTask) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TbCoinTask) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TbCoinTask) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *TbCoinTask) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TbCoinTask) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TbCoinTask) GetSysCreated() string {
	if x != nil {
		return x.SysCreated
	}
	return ""
}

func (x *TbCoinTask) GetSysUpdated() string {
	if x != nil {
		return x.SysUpdated
	}
	return ""
}

func (x *TbCoinTask) GetSysStatus() int32 {
	if x != nil {
		return x.SysStatus
	}
	return 0
}

// tb_coin_user
type TbCoinUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid        int32  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Coins      int32  `protobuf:"varint,3,opt,name=coins,proto3" json:"coins,omitempty"`
	SysCreated string `protobuf:"bytes,4,opt,name=sys_created,json=sysCreated,proto3" json:"sys_created,omitempty"`
	SysUpdated string `protobuf:"bytes,5,opt,name=sys_updated,json=sysUpdated,proto3" json:"sys_updated,omitempty"`
}

func (x *TbCoinUser) Reset() {
	*x = TbCoinUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TbCoinUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbCoinUser) ProtoMessage() {}

func (x *TbCoinUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbCoinUser.ProtoReflect.Descriptor instead.
func (*TbCoinUser) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{20}
}

func (x *TbCoinUser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TbCoinUser) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TbCoinUser) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *TbCoinUser) GetSysCreated() string {
	if x != nil {
		return x.SysCreated
	}
	return ""
}

func (x *TbCoinUser) GetSysUpdated() string {
	if x != nil {
		return x.SysUpdated
	}
	return ""
}

// tb_grade_info
type TbGradeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Score       int32  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Expired     int32  `protobuf:"varint,5,opt,name=expired,proto3" json:"expired,omitempty"`
	SysCreated  string `protobuf:"bytes,6,opt,name=sys_created,json=sysCreated,proto3" json:"sys_created,omitempty"`
	SysUpdated  string `protobuf:"bytes,7,opt,name=sys_updated,json=sysUpdated,proto3" json:"sys_updated,omitempty"`
}

func (x *TbGradeInfo) Reset() {
	*x = TbGradeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TbGradeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbGradeInfo) ProtoMessage() {}

func (x *TbGradeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbGradeInfo.ProtoReflect.Descriptor instead.
func (*TbGradeInfo) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{21}
}

func (x *TbGradeInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TbGradeInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TbGradeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TbGradeInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TbGradeInfo) GetExpired() int32 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *TbGradeInfo) GetSysCreated() string {
	if x != nil {
		return x.SysCreated
	}
	return ""
}

func (x *TbGradeInfo) GetSysUpdated() string {
	if x != nil {
		return x.SysUpdated
	}
	return ""
}

// tb_grade_privilege
type TbGradePrivilege struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GradeId     int32  `protobuf:"varint,2,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Product     string `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Function    string `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Expired     int32  `protobuf:"varint,6,opt,name=expired,proto3" json:"expired,omitempty"`
	SysCreated  string `protobuf:"bytes,7,opt,name=sys_created,json=sysCreated,proto3" json:"sys_created,omitempty"`
	SysUpdated  string `protobuf:"bytes,8,opt,name=sys_updated,json=sysUpdated,proto3" json:"sys_updated,omitempty"`
	SysStatus   int32  `protobuf:"varint,9,opt,name=sys_status,json=sysStatus,proto3" json:"sys_status,omitempty"`
}

func (x *TbGradePrivilege) Reset() {
	*x = TbGradePrivilege{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TbGradePrivilege) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbGradePrivilege) ProtoMessage() {}

func (x *TbGradePrivilege) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbGradePrivilege.ProtoReflect.Descriptor instead.
func (*TbGradePrivilege) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{22}
}

func (x *TbGradePrivilege) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TbGradePrivilege) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *TbGradePrivilege) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *TbGradePrivilege) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *TbGradePrivilege) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TbGradePrivilege) GetExpired() int32 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *TbGradePrivilege) GetSysCreated() string {
	if x != nil {
		return x.SysCreated
	}
	return ""
}

func (x *TbGradePrivilege) GetSysUpdated() string {
	if x != nil {
		return x.SysUpdated
	}
	return ""
}

func (x *TbGradePrivilege) GetSysStatus() int32 {
	if x != nil {
		return x.SysStatus
	}
	return 0
}

// tb_grade_user
type TbGradeUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid        int32  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	GradeId    int32  `protobuf:"varint,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Expired    string `protobuf:"bytes,4,opt,name=expired,proto3" json:"expired,omitempty"`
	Score      int32  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	SysCreated string `protobuf:"bytes,6,opt,name=sys_created,json=sysCreated,proto3" json:"sys_created,omitempty"`
	SysUpdated string `protobuf:"bytes,7,opt,name=sys_updated,json=sysUpdated,proto3" json:"sys_updated,omitempty"`
}

func (x *TbGradeUser) Reset() {
	*x = TbGradeUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_groth_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TbGradeUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbGradeUser) ProtoMessage() {}

func (x *TbGradeUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_groth_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbGradeUser.ProtoReflect.Descriptor instead.
func (*TbGradeUser) Descriptor() ([]byte, []int) {
	return file_user_groth_proto_rawDescGZIP(), []int{23}
}

func (x *TbGradeUser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TbGradeUser) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TbGradeUser) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *TbGradeUser) GetExpired() string {
	if x != nil {
		return x.Expired
	}
	return ""
}

func (x *TbGradeUser) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TbGradeUser) GetSysCreated() string {
	if x != nil {
		return x.SysCreated
	}
	return ""
}

func (x *TbGradeUser) GetSysUpdated() string {
	if x != nil {
		return x.SysUpdated
	}
	return ""
}

var File_user_groth_proto protoreflect.FileDescriptor

var file_user_groth_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x44, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74,
	0x68, 0x2e, 0x54, 0x62, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f,
	0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x3f, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e,
	0x54, 0x62, 0x43, 0x6f, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x52, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x62, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x54, 0x62, 0x43, 0x6f,
	0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x5a, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x69, 0x6e, 0x22, 0x41, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x54, 0x62, 0x43, 0x6f, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x33, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x54,
	0x62, 0x47, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x17,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x54, 0x62, 0x47, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x63, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x41, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68,
	0x2e, 0x54, 0x62, 0x47, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x40, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x22, 0x43, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x54, 0x62, 0x47, 0x72, 0x61, 0x64, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9d, 0x01, 0x0a, 0x0c, 0x54, 0x62,
	0x43, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x79,
	0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0xd1, 0x01, 0x0a, 0x0a, 0x54, 0x62,
	0x43, 0x6f, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x79, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x79, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x79, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x73, 0x79, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x86, 0x01,
	0x0a, 0x0a, 0x54, 0x62, 0x43, 0x6f, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x69, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0xc7, 0x01, 0x0a, 0x0b, 0x54, 0x62, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x22, 0x90, 0x02, 0x0a, 0x10, 0x54, 0x62, 0x47, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x76,
	0x69, 0x6c, 0x65, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x79, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x79, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x54, 0x62, 0x47, 0x72, 0x61, 0x64, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x32, 0x82, 0x03, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x5c, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1c, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x4e, 0x0a,
	0x0c, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x57, 0x0a,
	0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x22, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74,
	0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6f, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f,
	0x69, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69,
	0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x13, 0x3a, 0x01, 0x2a, 0x22, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x32, 0xdd, 0x03, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x60, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x12, 0x60, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x12, 0x25, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74,
	0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x76, 0x69,
	0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x12, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x12,
	0x25, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x77, 0x74, 0x68, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x51, 0x0a, 0x0d, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x57,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x22, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x77,
	0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x10, 0x5a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_user_groth_proto_rawDescOnce sync.Once
	file_user_groth_proto_rawDescData = file_user_groth_proto_rawDesc
)

func file_user_groth_proto_rawDescGZIP() []byte {
	file_user_groth_proto_rawDescOnce.Do(func() {
		file_user_groth_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_groth_proto_rawDescData)
	})
	return file_user_groth_proto_rawDescData
}

var file_user_groth_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_user_groth_proto_goTypes = []any{
	(*ListTasksRequest)(nil),          // 0: UserGrowth.ListTasksRequest
	(*ListTasksReply)(nil),            // 1: UserGrowth.ListTasksReply
	(*UserCoinInfoRequest)(nil),       // 2: UserGrowth.UserCoinInfoRequest
	(*UserCoinInfoReply)(nil),         // 3: UserGrowth.UserCoinInfoReply
	(*UserCoinDetailsRequest)(nil),    // 4: UserGrowth.UserCoinDetailsRequest
	(*UserCoinDetailsReply)(nil),      // 5: UserGrowth.UserCoinDetailsReply
	(*UserCoinChangeRequest)(nil),     // 6: UserGrowth.UserCoinChangeRequest
	(*UserCoinChangeReply)(nil),       // 7: UserGrowth.UserCoinChangeReply
	(*ListGradesRequest)(nil),         // 8: UserGrowth.ListGradesRequest
	(*ListGradesReply)(nil),           // 9: UserGrowth.ListGradesReply
	(*ListGradePrivilegeRequest)(nil), // 10: UserGrowth.ListGradePrivilegeRequest
	(*ListGradePrivilegeReply)(nil),   // 11: UserGrowth.ListGradePrivilegeReply
	(*CheckUserPrivilegeRequest)(nil), // 12: UserGrowth.CheckUserPrivilegeRequest
	(*CheckUserPrivilegeReply)(nil),   // 13: UserGrowth.CheckUserPrivilegeReply
	(*UserGradeInfoRequest)(nil),      // 14: UserGrowth.UserGradeInfoRequest
	(*UserGradeInfoReply)(nil),        // 15: UserGrowth.UserGradeInfoReply
	(*UserGradeChangeRequest)(nil),    // 16: UserGrowth.UserGradeChangeRequest
	(*UserGradeChangeReply)(nil),      // 17: UserGrowth.UserGradeChangeReply
	(*TbCoinDetail)(nil),              // 18: UserGrowth.TbCoinDetail
	(*TbCoinTask)(nil),                // 19: UserGrowth.TbCoinTask
	(*TbCoinUser)(nil),                // 20: UserGrowth.TbCoinUser
	(*TbGradeInfo)(nil),               // 21: UserGrowth.TbGradeInfo
	(*TbGradePrivilege)(nil),          // 22: UserGrowth.TbGradePrivilege
	(*TbGradeUser)(nil),               // 23: UserGrowth.TbGradeUser
}
var file_user_groth_proto_depIdxs = []int32{
	19, // 0: UserGrowth.ListTasksReply.dataList:type_name -> UserGrowth.TbCoinTask
	20, // 1: UserGrowth.UserCoinInfoReply.data:type_name -> UserGrowth.TbCoinUser
	18, // 2: UserGrowth.UserCoinDetailsReply.dataList:type_name -> UserGrowth.TbCoinDetail
	20, // 3: UserGrowth.UserCoinChangeReply.user:type_name -> UserGrowth.TbCoinUser
	21, // 4: UserGrowth.ListGradesReply.dataList:type_name -> UserGrowth.TbGradeInfo
	22, // 5: UserGrowth.ListGradePrivilegeReply.dataList:type_name -> UserGrowth.TbGradePrivilege
	21, // 6: UserGrowth.UserGradeInfoReply.data:type_name -> UserGrowth.TbGradeInfo
	23, // 7: UserGrowth.UserGradeChangeReply.data:type_name -> UserGrowth.TbGradeUser
	0,  // 8: UserGrowth.UserCoin.ListTasks:input_type -> UserGrowth.ListTasksRequest
	2,  // 9: UserGrowth.UserCoin.UserCoinInfo:input_type -> UserGrowth.UserCoinInfoRequest
	4,  // 10: UserGrowth.UserCoin.UserCoinDetails:input_type -> UserGrowth.UserCoinDetailsRequest
	6,  // 11: UserGrowth.UserCoin.UserCoinChange:input_type -> UserGrowth.UserCoinChangeRequest
	8,  // 12: UserGrowth.UserGrade.ListGrades:input_type -> UserGrowth.ListGradesRequest
	10, // 13: UserGrowth.UserGrade.ListGradePrivilege:input_type -> UserGrowth.ListGradePrivilegeRequest
	12, // 14: UserGrowth.UserGrade.CheckUserPrivilege:input_type -> UserGrowth.CheckUserPrivilegeRequest
	14, // 15: UserGrowth.UserGrade.UserGradeInfo:input_type -> UserGrowth.UserGradeInfoRequest
	16, // 16: UserGrowth.UserGrade.UserGradeChange:input_type -> UserGrowth.UserGradeChangeRequest
	1,  // 17: UserGrowth.UserCoin.ListTasks:output_type -> UserGrowth.ListTasksReply
	3,  // 18: UserGrowth.UserCoin.UserCoinInfo:output_type -> UserGrowth.UserCoinInfoReply
	5,  // 19: UserGrowth.UserCoin.UserCoinDetails:output_type -> UserGrowth.UserCoinDetailsReply
	7,  // 20: UserGrowth.UserCoin.UserCoinChange:output_type -> UserGrowth.UserCoinChangeReply
	9,  // 21: UserGrowth.UserGrade.ListGrades:output_type -> UserGrowth.ListGradesReply
	11, // 22: UserGrowth.UserGrade.ListGradePrivilege:output_type -> UserGrowth.ListGradePrivilegeReply
	13, // 23: UserGrowth.UserGrade.CheckUserPrivilege:output_type -> UserGrowth.CheckUserPrivilegeReply
	15, // 24: UserGrowth.UserGrade.UserGradeInfo:output_type -> UserGrowth.UserGradeInfoReply
	17, // 25: UserGrowth.UserGrade.UserGradeChange:output_type -> UserGrowth.UserGradeChangeReply
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_groth_proto_init() }
func file_user_groth_proto_init() {
	if File_user_groth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_groth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListTasksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoinInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoinInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoinDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoinDetailsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoinChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UserCoinChangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListGradesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListGradesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListGradePrivilegeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListGradePrivilegeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CheckUserPrivilegeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CheckUserPrivilegeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*UserGradeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*UserGradeInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*UserGradeChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UserGradeChangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*TbCoinDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*TbCoinTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*TbCoinUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*TbGradeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*TbGradePrivilege); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_groth_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*TbGradeUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_groth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_groth_proto_goTypes,
		DependencyIndexes: file_user_groth_proto_depIdxs,
		MessageInfos:      file_user_groth_proto_msgTypes,
	}.Build()
	File_user_groth_proto = out.File
	file_user_groth_proto_rawDesc = nil
	file_user_groth_proto_goTypes = nil
	file_user_groth_proto_depIdxs = nil
}
